services:
- docker:dind
stages:
- build
build:
  stage: build
  image: docker:latest
  rules:
  - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    changes:
    - Makefile
    - make/*.mk
    - docker/*/Makefile
    - docker/*/Dockerfile
    - $CI_CONFIG_PATH
  variables:
    REGISTRY: $CI_REGISTRY
    REGISTRY_USERNAME: $GITLAB_USERNAME
    REGISTRY_PASSWORD: $GITLAB_TOKEN
    IMAGE_NAME_PREFIX: $CI_REGISTRY/$GITLAB_USERNAME/$CI_PROJECT_NAME/
    IMAGE_REVISION: $CI_COMMIT_SHORT_SHA
    IMAGE_SOURCE: $CI_PROJECT_URL
    IMAGE_URL: $CI_PROJECT_URL/container_registry/
  before_script:
  - apk add --no-cache bash make
  script:
  - make login build push
