image: docker:latest
services:
- docker:dind
stages:
- build
before_script:
- apk add --no-cache bash make
build:
  stage: build
  rules:
  - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    changes:
    - Makefile
    - make/*.mk
    - docker/*/Makefile
    - docker/*/Dockerfile
    - $CI_CONFIG_PATH
  variables:
    DOCKER_REGISTRY: $CI_REGISTRY
    DOCKER_USERNAME: $GITLAB_USERNAME
    DOCKER_PASSWORD: $GITLAB_TOKEN
    IMAGE_NAME_PREFIX: $CI_REGISTRY/$GITLAB_USERNAME/$CI_PROJECT_NAME/
    SOURCE: $CI_PROJECT_URL
    URL: $CI_PROJECT_URL/container_registry/
  script:
  - make login build push
