services:
  clang:
    image: invasy/dev-env-clang:latest
    build:
      context: docker/clang
    cap_add:
    - SYS_ADMIN
    container_name: dev_env_clang
    hostname: clang
    domainname: invasy.dev
    ports:
    - "127.0.0.1:22001:22"
    restart: unless-stopped
  gcc:
    image: invasy/dev-env-gcc:latest
    build:
      context: docker/gcc
    cap_add:
    - SYS_ADMIN
    container_name: dev_env_gcc
    hostname: gcc
    domainname: invasy.dev
    ports:
    - "127.0.0.1:22002:22"
    restart: unless-stopped
